{% set name = "anaflow" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 150e1901c4ccbba14066b7ec607bba393a9cab43ae878747937417f4d50649f7

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - scipy                                  # [build_platform != target_platform]
    - pentapy                                # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=64
    - setuptools_scm >=7
    - cython >=3.0
    - numpy
    - scipy
    - pentapy >=1.1.0
  run:
    - python
    - numpy >=1.20.0
    - {{ pin_compatible('scipy') }}
    - pentapy >=1.1.0

test:
  imports:
    - anaflow
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/AnaFlow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AnaFlow - analytical solutions for the groundwater-flow equation.
  doc_url: https://anaflow.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/AnaFlow

extra:
  recipe-maintainers:
    - MuellerSeb
