{% set name = "anaflow" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf0173e7e95c4ccea4db0444eabeff30463a41ab752c9a2fbd1d02aff36aca7b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=64
    - setuptools_scm >=7
  run:
    - python >={{ python_min }}
    - numpy >=1.14.5
    - pentapy >=1.1.0
    - scipy >=1.1.0

test:
  imports:
    - anaflow
  requires:
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/AnaFlow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: AnaFlow - analytical solutions for the groundwater-flow equation.
  doc_url: https://anaflow.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/AnaFlow

extra:
  recipe-maintainers:
    - MuellerSeb
